# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Text-Language-Guess
version:      0.01
version_from: lib/Text/Language/Guess.pm
installdirs:  site
requires:
    File::Basename:                0
    File::Spec:                    0
    Lingua::StopWords:             0
    Text::ExtractWords:            0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
